version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: youtube-trends-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: youtube_trends
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - youtube-trends-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: youtube-trends-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/youtube_trends?authSource=admin
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - youtube-trends-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: youtube-trends-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - youtube-trends-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: youtube-trends-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - youtube-trends-network

volumes:
  mongodb_data:

networks:
  youtube-trends-network:
    driver: bridge
